### ISSUE TITLE
Keyboard combinations won't work in some apps

### ISSUE THREAD

**Issue by andreicon** [DustinBrett/daedalOS#41] opened 2022-01-29 13:47 UTC
I tried playing doom and when using alt+left to strafe left the browser will pick that up as "go back".

these keyboard events should be caught and their default behavior should not be allowed to execute.

check out this pen: https://codepen.io/andreicon/pen/PoOPWWy

**Comment by DustinBrett** [comment] 2022-01-29 16:47
Thanks for this report. I will work with js-dos and other ideas to try and limit this. I need to upgrade js-dos in general as it's had a lot of improvements recently I don't have.

**Comment by DustinBrett** [comment] 2022-03-01 04:26
Thanks again for this report but I've decided it's a Won't fix for now.

**Closed by DustinBrett** 2022-03-01 04:26 UTC

**Comment by hello-smile6** [comment] 2022-03-01 04:32
Couldn't you just send keystrokes to js-dos directly?

**Comment by DustinBrett** [comment] 2022-03-01 04:45
Keystrokes are being sent. The issue is some key combos are taken by the browser, such as the ability for a user to go back by pressing alt+left. For now I dont desire to block this.
