### ISSUE TITLE
Error when running app in uwp visual studio with index.html file

### ISSUE THREAD

**Issue by PurpleVoidEpic** [DustinBrett/daedalOS#210] opened 2022-09-30 18:50 UTC
JavaScript critical error at line 1, column 26599 in ms-appx://desktop/_next/static/chunks/pages/_app-b9e048d72879c22e.js\n\nSCRIPT1005: Expected '('

**Comment by PurpleVoidEpic** [comment] 2022-09-30 19:06
yarn yarn build and yarn export is how is created the index html file

**Comment by PurpleVoidEpic** [comment] 2022-09-30 19:17
i press the green play button in visual studio then the app should work like the website im using visual studio 2017 and made uwp js app then imported all the files including index.html.

**Comment by DustinBrett** [comment] 2022-09-30 19:27
I am not sure to be honest on using html files that way with visual studio 2017, nor do I know much about uwp js apps. The files should work in general so maybe that error is about a failure to parse the code. I can't say why. Try to load the `index.html` files other ways and see if you get the same error and maybe send a screenshot of the exact spot of the error and what is happening when you load it.

**Comment by DustinBrett** [comment] 2022-10-02 16:11
I'll keep this open for a while in case the issue persists. But if we can't debug it I may close this as the issue sounds specific to your case. The `index.html` works when built and ran on a web server such as nginx.

**Comment by DustinBrett** [comment] 2022-10-06 15:52
Feel free to reopen this issue if you have more details to work with. As is, the build works when compiled so I would say the issue is related to the way you are loading it.

**Closed by DustinBrett** 2022-10-06 15:52 UTC
