### ISSUE TITLE
Dragging an icon over another makes the dragged one disappear in the desktop

### ISSUE THREAD

**Issue by JoelBonetR** [DustinBrett/daedalOS#268] opened 2023-02-06 19:37 UTC
I've tested the desktop and one random folder.
The bug happens in desktop but not in the folder, so I assume it is an isolated issue.

**Comment by DustinBrett** [comment] 2023-02-06 19:44
This is not happening to me on Chrome. Do you mean if you drop the icon on a folder icon? In that case it sends the shortcut/file to the folder.

**Comment by JoelBonetR** [comment] 2023-02-06 19:46
Sorry, was about to update the issue with more info.

It looks like the dragged item gets stored inside whatever the target icon must be, like if you drag an image or shortcut over "My PC", the item gets stored inside MyPC.

Tested in Chrome (latest) over MacOS (latest)

**Comment by DustinBrett** [comment] 2023-02-06 19:47
Ok cool, that is actually as intended. It is the same behavior as happens in Windows 10. Or is it acting in some way unexpected from that?

**Comment by JoelBonetR** [comment] 2023-02-06 19:54
If I try to drop anything inside **My PC** I get a `cursor: not-allowed;` and i'm not able to drop anything on it.

I don't have any win 10 here right now but tested with Win 11 and I'm pretty sure it happens the same on Win 10 or any other I used since win 98.

If I'm wrong, sorry for the inconvenience.

**Comment by DustinBrett** [comment] 2023-02-06 19:57
On Chrome desktop I am able to drag/drop into My PC. Are you using a different setup?

![image](https://user-images.githubusercontent.com/16656318/217072089-f2dfbfa1-b80f-48fd-b655-562e0f728bd3.png)

**Comment by JoelBonetR** [comment] 2023-02-06 20:00
**I am able too**, but if it's supposed to mimic **Windows** OS, it should **not** be possible to drop things inside "My PC"

**Comment by DustinBrett** [comment] 2023-02-06 20:03
Ah I see what you are saying with that. Well in that case ya it is the exception I guess, as for me `My PC` leads to `/` which would be like if it went directly to `C:\`, so I am ok with this inconsistency.

But anything beyond that I would indeed prefer to match Windows 10 as much as possible, except when it might make sense not to.

**Comment by DustinBrett** [comment] 2023-02-06 20:20
Thanks very much! I'll close this for now but if you see anything else feel free to re-open or make new issues. I appreciate the feedback!

**Closed by DustinBrett** 2023-02-06 20:20 UTC
